In [29]:
import pandas as pd

In [30]:
years = [i for i in range(2021, 2024)]

In [31]:
def clean_file(orig_dir, year):
    path = f"{orig_dir}/{year}_LoL_esports_match_data_from_OraclesElixir.csv"
    df = pd.read_csv(path, index_col=0)
    df = df[df['datacompleteness'].str.contains('complete')]
    df = df[df['position'].str.contains('team')]
    del df['datacompleteness']
    del df['participantid']
    del df['teamid']
    del df['position']
    del df['teamkills']
    df = df.dropna(subset=['teamname', 'damagetochampions', 'dragons', 'goldat15', 'minionkills', 'visionscore', 'heralds', 'turretplates'])
    df = df[~df['teamname'].str.contains('unknown team')]
    for s in ['quadrakills', 'pentakills', 'chemtechs', 'hextechs', 'elders', 'opp_elders', 'firstmidtower', 'firstbaron', 'inhibitors', 'opp_inhibitors']:
        df[s][pd.isnull(df[s])] = 0
    df = df.sort_values('date')
    df = df.reset_index()
    return df

In [32]:
# df19 = clean_file('data', 2019)
# df20 = clean_file("data", 2020)
# df21 = clean_file("data", 2021)
# df22 = clean_file("data", 2022)
df = clean_file("data", 2023)
years.reverse()
for year in years:
    df_temp = clean_file("data", year)
    df = pd.concat([df_temp, df], ignore_index=True)

/var/folders/_6/_dxmrgx91s127f4vpswlc2700000gn/T/ipykernel_70838/3992710063.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, index_col=0)
/var/folders/_6/_dxmrgx91s127f4vpswlc2700000gn/T/ipykernel_70838/3992710063.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, index_col=0)
/var/folders/_6/_dxmrgx91s127f4vpswlc2700000gn/T/ipykernel_70838/3992710063.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, index_col=0)

In [33]:
# df = pd.concat([df19, df20, df21, df22, df23], ignore_index=True)
df = df.sort_values('date').reset_index(drop=True)
df

,gameid,url,league,year,split,playoffs,date,game,patch,side,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,NA1_3961909585,https://matchhistory.na.leagueoflegends.com/en...,UPL,2021,Summer,0,2021-07-03 00:09:38,1.0,11.13,Blue,...,542.0,-1644.0,-1474.0,-81.0,4.0,3.0,2.0,2.0,3.0,4.0
1,NA1_3961909585,https://matchhistory.na.leagueoflegends.com/en...,UPL,2021,Summer,0,2021-07-03 00:09:38,1.0,11.13,Red,...,461.0,1644.0,1474.0,81.0,2.0,3.0,4.0,4.0,3.0,2.0
2,NA1_3961869577,https://matchhistory.na.leagueoflegends.com/en...,UPL,2021,Summer,0,2021-07-03 00:09:54,1.0,11.13,Blue,...,469.0,-4879.0,-3489.0,-25.0,4.0,5.0,10.0,10.0,17.0,4.0
3,NA1_3961869577,https://matchhistory.na.leagueoflegends.com/en...,UPL,2021,Summer,0,2021-07-03 00:09:54,1.0,11.13,Red,...,444.0,4879.0,3489.0,25.0,10.0,17.0,4.0,4.0,5.0,10.0
4,NA1_3964329988,https://matchhistory.na.leagueoflegends.com/en...,UPL,2021,Summer,0,2021-07-03 00:18:04,1.0,11.13,Blue,...,425.0,-6000.0,-1246.0,-34.0,5.0,4.0,12.0,12.0,17.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60168,ESPORTSTMNT01_3436660,NaN,NEXO,2024,Split 1,0,2023-11-20 19:05:47,1.0,13.22,Blue,...,461.0,-75.0,545.0,54.0,3.0,4.0,5.0,5.0,9.0,3.0
60169,ESPORTSTMNT01_3438678,NaN,NEXO,2024,Split 1,0,2023-11-20 19:59:21,2.0,13.22,Red,...,481.0,660.0,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0
60170,ESPORTSTMNT01_3438678,NaN,NEXO,2024,Split 1,0,2023-11-20 19:59:21,2.0,13.22,Blue,...,515.0,-660.0,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0
60171,ESPORTSTMNT01_3438678,NaN,NEXO,2024,Split 1,0,2023-11-20 19:59:21,2.0,13.22,Blue,...,515.0,-660.0,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0
60172,ESPORTSTMNT01_3438678,NaN,NEXO,2024,Split 1,0,2023-11-20 19:59:21,2.0,13.22,Red,...,481.0,660.0,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0

In [34]:
nulls = pd.isnull(df)
nulls = nulls.sum()
nulls = nulls[nulls > 0]
nulls

url                        57622
split                      15600
game                          80
playername                 60173
playerid                   60173
champion                   60173
ban1                         147
ban2                          92
ban3                         252
ban4                         181
ban5                         322
firstbloodkill             60173
firstbloodassist           60173
firstbloodvictim           60173
dragons (type unknown)     59519
damageshare                60173
earnedgoldshare            60173
total cs                   60173
monsterkillsownjungle      60173
monsterkillsenemyjungle    60173
dtype: int64

In [35]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]
valid_columns

Index(['gameid', 'league', 'year', 'playoffs', 'date', 'patch', 'side',
       'teamname', 'gamelength', 'result', 'kills', 'deaths', 'assists',
       'teamdeaths', 'doublekills', 'triplekills', 'quadrakills', 'pentakills',
       'firstblood', 'team kpm', 'ckpm', 'firstdragon', 'dragons',
       'opp_dragons', 'elementaldrakes', 'opp_elementaldrakes', 'infernals',
       'mountains', 'clouds', 'oceans', 'chemtechs', 'hextechs', 'elders',
       'opp_elders', 'firstherald', 'heralds', 'opp_heralds', 'firstbaron',
       'barons', 'opp_barons', 'firsttower', 'towers', 'opp_towers',
       'firstmidtower', 'firsttothreetowers', 'turretplates',
       'opp_turretplates', 'inhibitors', 'opp_inhibitors', 'damagetochampions',
       'dpm', 'damagetakenperminute', 'damagemitigatedperminute',
       'wardsplaced', 'wpm', 'wardskilled', 'wcpm', 'controlwardsbought',
       'visionscore', 'vspm', 'totalgold', 'earnedgold', 'earned gpm',
       'goldspent', 'gspd', 'minionkills', 'monsterkills', 'cspm', 'goldat10',
       'xpat10', 'csat10', 'opp_goldat10', 'opp_xpat10', 'opp_csat10',
       'golddiffat10', 'xpdiffat10', 'csdiffat10', 'killsat10', 'assistsat10',
       'deathsat10', 'opp_killsat10', 'opp_assistsat10', 'opp_deathsat10',
       'goldat15', 'xpat15', 'csat15', 'opp_goldat15', 'opp_xpat15',
       'opp_csat15', 'golddiffat15', 'xpdiffat15', 'csdiffat15', 'killsat15',
       'assistsat15', 'deathsat15', 'opp_killsat15', 'opp_assistsat15',
       'opp_deathsat15'],
      dtype='object')

In [36]:
df = df[valid_columns].copy()
df

,gameid,league,year,playoffs,date,patch,side,teamname,gamelength,result,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,NA1_3961909585,UPL,2021,0,2021-07-03 00:09:38,11.13,Blue,ConViction,1934324,1,...,542.0,-1644.0,-1474.0,-81.0,4.0,3.0,2.0,2.0,3.0,4.0
1,NA1_3961909585,UPL,2021,0,2021-07-03 00:09:38,11.13,Red,Mercenaries,1934324,0,...,461.0,1644.0,1474.0,81.0,2.0,3.0,4.0,4.0,3.0,2.0
2,NA1_3961869577,UPL,2021,0,2021-07-03 00:09:54,11.13,Blue,Striking Vipers Maestros,1934690,0,...,469.0,-4879.0,-3489.0,-25.0,4.0,5.0,10.0,10.0,17.0,4.0
3,NA1_3961869577,UPL,2021,0,2021-07-03 00:09:54,11.13,Red,RockTribeEsports,1934690,1,...,444.0,4879.0,3489.0,25.0,10.0,17.0,4.0,4.0,5.0,10.0
4,NA1_3964329988,UPL,2021,0,2021-07-03 00:18:04,11.13,Blue,Purdue University Northwest,1782343,0,...,425.0,-6000.0,-1246.0,-34.0,5.0,4.0,12.0,12.0,17.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60168,ESPORTSTMNT01_3436660,NEXO,2024,0,2023-11-20 19:05:47,13.22,Blue,Kawaii Kiwis,1940,1,...,461.0,-75.0,545.0,54.0,3.0,4.0,5.0,5.0,9.0,3.0
60169,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Red,Erfolg Esports,2464,0,...,481.0,660.0,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0
60170,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Blue,Kawaii Kiwis,2464,1,...,515.0,-660.0,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0
60171,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Blue,Kawaii Kiwis,2464,1,...,515.0,-660.0,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0
60172,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Red,Erfolg Esports,2464,0,...,481.0,660.0,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0

In [37]:
result = df.pop('result')
df.insert(len(df.columns), 'result', result)

In [38]:
def add_target(team):
    team['target'] = team['result'].shift(-1)
    return team

df = df.groupby('teamname', group_keys=False).apply(add_target)

In [39]:
df[df['teamname'] == 'T1']

,gameid,league,year,playoffs,date,patch,side,teamname,gamelength,kills,...,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,result,target
311,ESPORTSTMNT03_2054324,LCK,2021,0,2021-08-06 10:45:26,11.15,Blue,T1,2199,12,...,288.0,0.0,2.0,4.0,2.0,2.0,2.0,2.0,1,0.0
316,ESPORTSTMNT03_2074387,LCK,2021,0,2021-08-06 12:25:12,11.15,Red,T1,1872,7,...,-1401.0,-46.0,3.0,8.0,4.0,4.0,8.0,3.0,0,1.0
320,ESPORTSTMNT03_2074420,LCK,2021,0,2021-08-06 13:20:50,11.15,Blue,T1,1832,17,...,1865.0,68.0,4.0,12.0,1.0,1.0,0.0,4.0,1,1.0
505,ESPORTSTMNT03_2055160,LCK,2021,0,2021-08-08 11:00:53,11.15,Blue,T1,1976,12,...,-904.0,11.0,3.0,4.0,4.0,4.0,8.0,3.0,1,1.0
509,ESPORTSTMNT03_2055172,LCK,2021,0,2021-08-08 11:37:41,11.15,Red,T1,2247,8,...,-4087.0,-54.0,1.0,1.0,4.0,4.0,8.0,1.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60144,ESPORTSTMNT03_3228396,WLDs,2023,0,2023-11-19 08:56:48,13.19,Red,T1,1831,14,...,-208.0,58.0,2.0,5.0,4.0,4.0,6.0,3.0,1,1.0
60147,ESPORTSTMNT03_3227846,WLDs,2023,0,2023-11-19 09:51:16,13.19,Red,T1,1797,14,...,913.0,43.0,2.0,3.0,1.0,0.0,0.0,2.0,1,1.0
60148,ESPORTSTMNT03_3227846,WLDs,2023,0,2023-11-19 09:51:16,13.19,Red,T1,1797,14,...,913.0,43.0,2.0,3.0,1.0,0.0,0.0,2.0,1,1.0
60151,ESPORTSTMNT03_3227847,WLDs,2023,0,2023-11-19 10:44:06,13.19,Red,T1,1547,19,...,1357.0,25.0,3.0,7.0,3.0,3.0,6.0,3.0,1,1.0
60152,ESPORTSTMNT03_3227847,WLDs,2023,0,2023-11-19 10:44:06,13.19,Red,T1,1547,19,...,1357.0,25.0,3.0,7.0,3.0,3.0,6.0,3.0,1,NaN

In [40]:
df['target'][pd.isnull(df['target'])] = 2
df['target'] = df['target'].astype(int, errors='ignore')
df

/var/folders/_6/_dxmrgx91s127f4vpswlc2700000gn/T/ipykernel_70838/3500486044.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'][pd.isnull(df['target'])] = 2

,gameid,league,year,playoffs,date,patch,side,teamname,gamelength,kills,...,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,result,target
0,NA1_3961909585,UPL,2021,0,2021-07-03 00:09:38,11.13,Blue,ConViction,1934324,17,...,-1474.0,-81.0,4.0,3.0,2.0,2.0,3.0,4.0,1,1
1,NA1_3961909585,UPL,2021,0,2021-07-03 00:09:38,11.13,Red,Mercenaries,1934324,6,...,1474.0,81.0,2.0,3.0,4.0,4.0,3.0,2.0,0,0
2,NA1_3961869577,UPL,2021,0,2021-07-03 00:09:54,11.13,Blue,Striking Vipers Maestros,1934690,17,...,-3489.0,-25.0,4.0,5.0,10.0,10.0,17.0,4.0,0,1
3,NA1_3961869577,UPL,2021,0,2021-07-03 00:09:54,11.13,Red,RockTribeEsports,1934690,33,...,3489.0,25.0,10.0,17.0,4.0,4.0,5.0,10.0,1,0
4,NA1_3964329988,UPL,2021,0,2021-07-03 00:18:04,11.13,Blue,Purdue University Northwest,1782343,13,...,-1246.0,-34.0,5.0,4.0,12.0,12.0,17.0,5.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60168,ESPORTSTMNT01_3436660,NEXO,2024,0,2023-11-20 19:05:47,13.22,Blue,Kawaii Kiwis,1940,21,...,545.0,54.0,3.0,4.0,5.0,5.0,9.0,3.0,1,1
60169,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Red,Erfolg Esports,2464,20,...,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0,0,0
60170,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Blue,Kawaii Kiwis,2464,25,...,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0,1,1
60171,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Blue,Kawaii Kiwis,2464,25,...,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0,1,2
60172,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,Red,Erfolg Esports,2464,20,...,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0,0,2

In [41]:
df['side'].replace({'Blue': 1}, inplace=True)
df['side'].replace({'Red': 0}, inplace=True)
df

,gameid,league,year,playoffs,date,patch,side,teamname,gamelength,kills,...,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,result,target
0,NA1_3961909585,UPL,2021,0,2021-07-03 00:09:38,11.13,1,ConViction,1934324,17,...,-1474.0,-81.0,4.0,3.0,2.0,2.0,3.0,4.0,1,1
1,NA1_3961909585,UPL,2021,0,2021-07-03 00:09:38,11.13,0,Mercenaries,1934324,6,...,1474.0,81.0,2.0,3.0,4.0,4.0,3.0,2.0,0,0
2,NA1_3961869577,UPL,2021,0,2021-07-03 00:09:54,11.13,1,Striking Vipers Maestros,1934690,17,...,-3489.0,-25.0,4.0,5.0,10.0,10.0,17.0,4.0,0,1
3,NA1_3961869577,UPL,2021,0,2021-07-03 00:09:54,11.13,0,RockTribeEsports,1934690,33,...,3489.0,25.0,10.0,17.0,4.0,4.0,5.0,10.0,1,0
4,NA1_3964329988,UPL,2021,0,2021-07-03 00:18:04,11.13,1,Purdue University Northwest,1782343,13,...,-1246.0,-34.0,5.0,4.0,12.0,12.0,17.0,5.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60168,ESPORTSTMNT01_3436660,NEXO,2024,0,2023-11-20 19:05:47,13.22,1,Kawaii Kiwis,1940,21,...,545.0,54.0,3.0,4.0,5.0,5.0,9.0,3.0,1,1
60169,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,0,Erfolg Esports,2464,20,...,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0,0,0
60170,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,1,Kawaii Kiwis,2464,25,...,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0,1,1
60171,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,1,Kawaii Kiwis,2464,25,...,-1568.0,-34.0,4.0,7.0,2.0,2.0,0.0,4.0,1,2
60172,ESPORTSTMNT01_3438678,NEXO,2024,0,2023-11-20 19:59:21,13.22,0,Erfolg Esports,2464,20,...,1568.0,34.0,2.0,0.0,4.0,4.0,7.0,2.0,0,2

In [42]:
df.to_csv('cleaned_data.csv')